### ISSUE TITLE
Error a la hora de checar la versión previamente instalada de runnerty y a la hora de mandar a ejecutar el proyecto clonado

### ISSUE THREAD

**Issue by jmcsoberano** [Coderty/runnerty-quick-start#2]
La instalación del runnerty de manera global se installa, pero a tanto a la hora de checar la version, como despues de instalar las dependencias del proyecto clonado, manda error

**C:\Git\temp\Coderty>runnerty --version**
**C:\Users\Tokens Cammor\AppData\Roaming\npm\node_modules\runnerty\lib\init.js:30
    .then(async function (fileConfig) {
          ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Tokens Cammor\AppData\Roaming\npm\node_modules\runnerty\lib\app.js:5:12)
    at Module._compile (module.js:571:32)**

**Comment by alo** [comment]
Hola @jmcsoberano !

Gracias por informar. Ya está resuelto, puedes descargarte la última versión de Runnerty con el comando:

```
npm i -g runnerty
```

Si actualizas el proyecto el problema debería estar resuelto. 

 Si lo ejecutas deberías ver como cada minuto se escribe una línea en el archivo **test.log** con un **hello word!**

En breve iremos publicando la documentación para que podáis sacarle el máximo partido a la herramienta. 

Saludos y gracias!
